workspace/MusicReview/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :albums do
  	collection do
  		get 'search'
  	end
  	resources :reviews, except: [:show, :index]
  end

  root 'albums#index'


end

workspace/MusicReview/app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user
	has_many :reviews
	searchkick
# paperclip requirements just copy and paste
	has_attached_file :image, styles: { medium: "300x300>", thumb: "300x300#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

workspace/MusicReview/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
end

workspace/MusicReview/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :reviews, dependent: :destroy       
end

workspace/MusicReview/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @albums = Album.all
  end

  def search
    if params[:search].present?
      @albums = Album.search(params[:search])
    else
      @albums = Album.all
    end   
  end

  def show
    @reviews = Review.where(album_id: @album.id).order('created_at DESC')

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end


  def new
    @album = current_user.albums.build
  end

  def edit
  end


  def create
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:artist, :album, :description, :release, :rating, :image)
    end
end

workspace/MusicReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/MusicReview/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_album


  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.album_id = @album.id

    if @review.save
      redirect_to @album
    else
      render 'new'
    end

  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private

    def set_review
      @review = Review.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
  end  

workspace/MusicReview/app/helpers/albums_helper.rb
module AlbumsHelper
end

workspace/MusicReview/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/MusicReview/app/helpers/reviews_helper.rb
module ReviewsHelper
end

workspace/MusicReview/app/views/albums/_form.html.erb
<%= form_for @album, html: { multipart: true } do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :release %><br>
    <%= f.text_field :release %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workspace/MusicReview/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

workspace/MusicReview/app/views/albums/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron text-center">
    <h1>My First Real RoR app - Music Review</h1>
    <p>Relying heavily on RoR guides, google search, Stack Overflow and wise men of RoR, this is my first web app, where you can Sign In & Out, write a review for an album, upload pictures (500 x 500 works best) and add ratings. Ratings are converted to stars with raly. js.</p>
    <p><%= link_to "Sign Up To Write a Review", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
<% end %>

<div class="row">
  <% @albums.each do |album |%>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag album.image.url(:medium), class: 'image'), album %>
      </div>
    </div>
  <% end %>
</div>

workspace/MusicReview/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

workspace/MusicReview/app/views/albums/search.html.erb
<div class="row">
  <% @albums.each do |album |%>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag album.image.url(:medium), class: 'image'), album %>
      </div>
    </div>
  <% end %>
</div>

workspace/MusicReview/app/views/albums/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @album.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title: <%= @album.artist %></strong></td>
                <td><%= @album.album %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @album.description %></td>
              </tr>
              <tr>
                <td><strong>Release:</strong></td>
                <td><%= @album.release %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @album.rating %></td>
              </tr>
            </tbody>
          </table>
          
            <%= link_to "Write a Review", new_album_review_path(@album) %>
          </div>
        </div>
        <div class='col-md-7 col-md-offset-1'>
          <h1 class='review_title'><%= @album.artist %></h1>
          <p><%= @album.description %></p>

          <% if @reviews.blank? %>
            <h3>No reviews just yet, would you like to add the first?</h3>
          <%= link_to 'Write Review', new_album_review_path(@album), class: 'btn btn-danger' %>
          <% else %>
            <% @reviews.each do |review| %>
            <div class="reviews">
            <div class="star-rating" data-score= <%= review.rating %>></div>
            <p><%= review.comment %></p>
            </div>
        
            <% end %>
          <% end %>

       
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

workspace/MusicReview/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Music Album Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Album", new_album_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      
      <%= form_tag  search_albums_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
      <p>
        <%= text_field_tag :search, params[:search], class: "form-control" %>
        <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
      </p>
      <% end %>

      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

workspace/MusicReview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: 'alert alert-info') %>
	<% end %>	
<div class="container">
	<%= yield %>
</div>
</body>
</html>

workspace/MusicReview/app/views/reviews/_form.html.erb
<%= form_for([@album, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

workspace/MusicReview/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', album_path(@album) %>

workspace/MusicReview/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', album_path(@album) %>

workspace/MusicReview/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
	<strong>User</strong>
	<%= @review.user.email %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>